/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FolderInput: typeof import('./src/components/FolderInput/FolderInput.vue')['default']
    MenuSide: typeof import('./src/components/MenuSide/MenuSide.vue')['default']
    MenuSideItem: typeof import('./src/components/MenuSide/MenuSideItem.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputGroup: typeof import('tdesign-vue-next')['InputGroup']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TParagraph: typeof import('tdesign-vue-next')['Paragraph']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
